theme: jekyll-theme-cayman
gem "github-pages", group: :jekyll_plugins
title: [The title of your site]
description: [A short description of your site's purpose]
show_downloads: ["true" or "false" to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]
---
---

@imp
